server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ucb-judge
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none

eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8711/eureka/

keycloak:
  auth-server-url: http://localhost:8090
  autodetect-bearer-only: true
  credentials:
    secret: CdxeNJUUwQ7MJr0wnkcxTGuQIdkx4tTH
  realm: ucb-judge
  resource: uj-contest
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - professor
      security-collections:
        - name: contests
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/v1/contest/*
#    - auth-roles:
#        - student
#        - professor
#        - uj-problems-access
#      security-collections:
#        - name: Get problems
#          methods:
#            - GET
#          patterns:
#            - /api/v1/problems

