server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ucb-judge
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true
#        properties:
#            dialect: org.hibernate.dialect.PostgreSQLDialect